### ISSUE TITLE
Typescript Complaint: Expected 0 type arguments, but got 1

### ISSUE THREAD

**Issue by saschahofmann** [tatethurston/nextjs-routes#73] opened 2022-09-30 09:47 UTC
Hi,
I am using the *nextjs-routes@0.1.0* with the `withRoutes` configuration but I am not sure it's working as expected.
I am seeing the following error 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/24508496/193243264-a92b2ce3-81b4-4aa3-a0a2-906c5dd1716e.png">

I also cannot see the nextjs-routes *nextjs-routes.d.ts* types or any addition to my *tsconfig.json*.

Any ideas what am I missing?

**Comment by tatethurston** [comment] 2022-09-30 21:37
Hey @saschahofmann could you send me your next config? And just to confirm, did you start (next dev) or build (next build) your next server?

**Comment by saschahofmann** [comment] 2022-09-30 21:45
Hi of course. Here is my *next.config.js*

```js
const withRoutes = require('nextjs-routes/config')()

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  sassOptions: {
    includePaths: ['./styles'],
  },
}

```
and yes I am running `next dev`

module.exports = withRoutes(nextConfig)

**Comment by tatethurston** [comment] 2022-09-30 21:56
Are you seeing any errors or warnings in your console when you run `next dev`? And are your pages in `pages` or `src/pages` or somewhere else?

**Comment by saschahofmann** [comment] 2022-09-30 22:04
No errors but I am running the command in the root directory  (where the next.config file resides) while the tsconfig lives in the *frontend* folder together with pages.

so really I am running `next dev frontend`

**Comment by tatethurston** [comment] 2022-09-30 22:08
Ah `nextjs-routes` expects your pages to be in either `pages` or `src/pages` relative to the root directory. It sounds like your pages are in `frontend/pages`?

**Comment by saschahofmann** [comment] 2022-09-30 22:33
I am having front- and backend in the same repo. I think in the beginning I needed the node modules available in the root directory to run a package to generate some code but actually I think I dont need it anymore.

More general I can see a scenario where maybe a configuration file (like a JSON schema or something) is shared between directories. For example, to generate some data types that are shared between Typescript and the API. Both code bases would need access to the file in which case it would be easier to have them installed root level?

**Comment by MariaSolOs** [comment] 2022-10-01 02:13
@saschahofmann I would suggest installing `nextjs-routes` locally per Next project. This package generates the typed path information for a single Next project, and because you cannot use Next's router for navigating to a route in another project, IMO it doesn't make sense to make this a shared configuration.

**Comment by saschahofmann** [comment] 2022-10-01 08:58
Sorry I might have explained it badly I am not using nextjs-routes (or nextjs) for two different projects. I was just explaining why I have the node_modules living in the root level rather than inside the `frontend` folder.

In my particular case for example,  I use the [openapi-typescript-codegen](https://www.npmjs.com/package/openapi-typescript-codegen) to generate the API client automatically. As I said above, I used a different approach before where I needed access to a file, with this approach I could simply move everything a level down. In that case, I can't for example run the build commands from the root level but that's not a big deal.

**Comment by saschahofmann** [comment] 2022-10-01 09:05
Interestingly I am not getting the `Could not find a Next.js pages directory. Expected to find either pages(1) or src/pages(2)` error 

```bash
$ next dev frontend
Debugger attached.
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
event - compiled client and server successfully in 1129 ms (179 modules)
wait  - compiling...
event - compiled client and server successfully in 215 ms (179 modules)
```

**Comment by MariaSolOs** [comment] 2022-10-01 16:58
@saschahofmann got it, thanks for explaining.

Does your `frontend` folder have a `package.json` file? And where are you placing the `next.config.js` file?

I don't know which is the specific setup that you have but [here](https://github.com/MariaSolOs/paradeigma) is a Yarn monorepo I'm working on where this package is working perfectly. The types are generated when running [this Next app](https://github.com/MariaSolOs/paradeigma/tree/88417dd2daec5468fb1575bb557a022558ae10c0/apps/paradeigma-web-app) and because of how Yarn works the dependencies are not living there either.

**Comment by saschahofmann** [comment] 2022-10-01 17:33
No I think that's the problem the yarn and next.config life in the root and the rest is in the front-end folder but I'm sure if I just move everything there it will work. Just wanted to note that maybe it's not the most uncommon case?

**Comment by MariaSolOs** [comment] 2022-10-01 17:39
@saschahofmann You're right. With the new options added to the `withRoutes` object this is a scenario that could be supported.

**Comment by saschahofmann** [comment] 2022-10-01 18:53
Cool I will try to move everything down just to check

**Comment by tatethurston** [comment] 2022-10-01 20:42
We could consider resolving the pages directory relative to the the next.config.js instead of package.json, which isn’t a big lift after the deprecation of the cli invocation. I’m hesitant to make this a dedication configuration option, because we should be able to find routes identical to next. What do you think @MariaSolOs ?

**Comment by MariaSolOs** [comment] 2022-10-02 01:04
@tatethurston sounds good to me!

**Comment by saschahofmann** [comment] 2022-10-03 08:34
Ok, I moved all the next and yarn stuff into the *frontend* folder and it works

**Comment by tatethurston** [comment] 2022-10-03 16:42
@saschahofmann could you outline what your project file tree looked like before the move? It sounds like previously it was this:

```
/repo
  /node_modules
  package.json
  next.config.js
  /backend
  /frontend
    /pages
    (no package.json)
```

**Comment by saschahofmann** [comment] 2022-10-04 07:35
Yes thats right the only other important file would be the tsconfig file that lives in */frontend*
```
/repo
  /node_modules
  package.json
  next.config.js
  /backend
  /frontend
    /pages
    tsconfig.json
    (no package.json)
```

**Comment by tatethurston** [comment] 2022-10-04 18:12
And Next is finding and building your pages as expected with that directory structure? Do you have anything else in that setup to make Next.js work?

**Closed** 2022-10-07 18:44 UTC

**Comment by alexgorbatchev** [comment] 2022-11-01 04:17
I'm seeing `Could not find a Next.js pages directory.` issue as well with a Nx generated Next.js, which doesn't include `package.json` file in the Next.js folder.

**Comment by tatethurston** [comment] 2022-11-01 05:22
@alexgorbatchev could you share an example with your project structure?

**Comment by alexgorbatchev** [comment] 2022-11-02 03:53
@tatethurston the problem is that nextjs-routes basically uses `process.cwd()` to find these directories. If you are using a monorepo, you are not guaranteed that `process.cwd() === <next.js app root>`. Looking at this a little bit more, it appears that Nx sets CWD to the monorepo root and doesn't like if you try to change that.

So, here's perhaps the ugliest hack one could imagine to get `nextjs-routes` to work with Nx monorepo. This basically monkeypatches `NextJSRoutesPlugin.apply` to `chdir` into Next.js and the out of it.

```js
const { withNx } = require('@nrwl/next/plugins/with-nx');

const nextConfig = {
  ...
};

const withNextjsRoutes = nextConfig =>
  // @ts-ignore
  require('nextjs-routes/config')({ __patchme: true })(nextConfig);

const patchNextjsRoutes = nextConfig => ({
  ...nextConfig,
  webpack: (config, context) => {
    const webpackConfig = nextConfig.webpack(config, context);

    for (const plugin of webpackConfig.plugins) {
      if (plugin.options && plugin.options.__patchme && !plugin.options.__patched) {
        const original = plugin.apply;

        plugin.apply = function () {
          const oldCWD = process.cwd();
          process.chdir(__dirname);
          original.apply(plugin);
          process.chdir(oldCWD);
        };

        plugin.options.__patched = true;
      }
    }
    return webpackConfig;
  },
});

module.exports = patchNextjsRoutes(withNextjsRoutes(withNx(nextConfig)));
```

**Comment by alexgorbatchev** [comment] 2022-11-02 04:06
I made a PR to avoid the hack.

**Comment by airtonix** [comment] 2023-04-25 03:08
@tatethurston why cant we just have a configuration option that lets us point to our pages/apps directory? 

```ts
//@ts-check
import * as path from 'path';
import compose from 'lodash/fp/compose.js';
import { withNx } from '@nrwl/next/plugins/with-nx.js';
import { createVanillaExtractPlugin } from '@vanilla-extract/next-plugin';
import { createContentlayerPlugin } from 'next-contentlayer';
import withRoutes from 'nextjs-routes/config';


/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: true,
  },
  swcMinify: true,
  experimental: { appDir: true },
};

export default compose(
  withNx,
  withRoutes({ pages: {
    type: 'app',
    root: path.join(__dirname, 'src', 'app')
  }}),
  createContentlayerPlugin({
    configPath: 'contentlayer.config.ts',
  }),
  createVanillaExtractPlugin({ identifiers: 'debug' })
)(nextConfig);

```

**Comment by tatethurston** [comment] 2023-04-25 03:18
> You should reopen this as the problem really hasn't been fixed.

@airtonix are you using the [configuration option described in the docs](https://github.com/tatethurston/nextjs-routes#configuration)? What issue are you running into?
