### ISSUE TITLE
npx nextjs-routes doesn't read NextConfig

### ISSUE THREAD

**Issue by sitch** [tatethurston/nextjs-routes#151] opened 2023-04-22 00:53 UTC
See: https://github.com/tatethurston/nextjs-routes/blob/main/src/cli.ts#L25

It should pull in the local config, like it does on the webpack hook so the `i18n` config gets properly typed

I've been getting weird false/positives locally since adding:
```json
// package.json
{
  "scripts": {
    "prebuild": "npx nextjs-routes"
  }
}
```

**Comment by tatethurston** [comment] 2023-04-22 01:08
Thanks @sitch this is a duplicate of https://github.com/tatethurston/nextjs-routes/issues/136

**Closed** 2023-04-22 01:08 UTC
